"""yarn.lock — Classic (v1) and Berry (v2+) formats (0.11.0 backlog).

Measured on 15.09.2026 (twin comparison, kettenlauf schnell #67): on the
streamlit frontend (a Berry lockfile with 1,591 entries) the collector read
0 components from yarn.lock — the reader knew only the classic
``version "x"`` line, Berry writes ``version: x``. The suite read 1,573.
"""

from __future__ import annotations

from pathlib import Path

from embtrace_sbom.sbom.scanner import scan_yarn_lock

_BERRY = '''# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"@adobe/css-tools@npm:^4.4.0":
  version: 4.4.0
  resolution: "@adobe/css-tools@npm:4.4.0"
  checksum: 10c0/d65ddc7
  languageName: node
  linkType: hard

"@streamlit/app@workspace:app":
  version: 0.0.0-use.local
  resolution: "@streamlit/app@workspace:app"
  dependencies:
    lodash: "npm:^4.17.21"
  languageName: unknown
  linkType: soft

"lodash@npm:^4.17.21, lodash@npm:^4.17.20":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"lodash@patch:lodash@npm%3A4.17.21#~/.yarn/patches/lodash.patch":
  version: 4.17.21
  resolution: "lodash@patch:lodash@npm%3A4.17.21#~/p.patch::version=4.17.21"
  languageName: node
  linkType: hard

"my-local-tool@link:./tools/my-local-tool::locator=app%40workspace%3A.":
  version: 0.0.0-use.local
  resolution: "my-local-tool@link:./tools/my-local-tool::locator=app%40workspace%3A."
  languageName: node
  linkType: soft
'''

_CLASSIC = '''# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0":
  version "7.24.2"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.2.tgz"
  integrity sha512-abc

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-def
'''


def test_berry_lockfile_yields_names_and_versions(tmp_path: Path) -> None:
    (tmp_path / "yarn.lock").write_text(_BERRY, encoding="utf-8")
    deps = scan_yarn_lock(tmp_path / "yarn.lock")
    got = {(d.name, d.version) for d in deps}
    assert got == {("@adobe/css-tools", "4.4.0"), ("lodash", "4.17.21")}
    assert all(d.ecosystem == "npm" for d in deps)
    assert {d.purl for d in deps} == {
        "pkg:npm/%40adobe/css-tools@4.4.0", "pkg:npm/lodash@4.17.21",
    }


def test_berry_metadata_and_local_entries_are_not_components(tmp_path: Path) -> None:
    (tmp_path / "yarn.lock").write_text(_BERRY, encoding="utf-8")
    names = {d.name for d in scan_yarn_lock(tmp_path / "yarn.lock")}
    assert "__metadata" not in names
    assert "@streamlit/app" not in names        # workspace member = own code
    assert "my-local-tool" not in names         # link: = own tree
    # the patched lodash resolves to the same version — one component
    assert sum(1 for d in scan_yarn_lock(tmp_path / "yarn.lock") if d.name == "lodash") == 1


def test_classic_lockfile_still_reads(tmp_path: Path) -> None:
    (tmp_path / "yarn.lock").write_text(_CLASSIC, encoding="utf-8")
    got = {(d.name, d.version) for d in scan_yarn_lock(tmp_path / "yarn.lock")}
    assert got == {("@babel/code-frame", "7.24.2"), ("lodash", "4.17.21")}

# The real shape measured in excalidraw (classic lockfile, 15.09.2026): a
# workspace member of the SAME monorepo, recorded with a registry URL. The
# name is the project's own package (packages/excalidraw/package.json says
# "name": "@excalidraw/excalidraw"), not a third-party component.
_CLASSIC_WORKSPACE = """# yarn lockfile v1


"@excalidraw/excalidraw@workspace:^":
  version "0.17.2"
  resolved "https://registry.yarnpkg.com/@excalidraw/excalidraw/-/excalidraw-0.17.2.tgz#9a636a1"
  integrity sha512-7pqUWD8

"react@^18.2.0":
  version "18.3.1"
  resolved "https://registry.yarnpkg.com/react/-/react-18.3.1.tgz#abc"
"""


def test_classic_workspace_member_is_not_a_third_party_component(tmp_path: Path) -> None:
    (tmp_path / "yarn.lock").write_text(_CLASSIC_WORKSPACE, encoding="utf-8")
    got = {(d.name, d.version) for d in scan_yarn_lock(tmp_path / "yarn.lock")}
    assert got == {("react", "18.3.1")}
